module Data exposing (randomKeyword, randomQuote)

import Array exposing (Array)
import Extra

randomKeyword : Float -> String
randomKeyword r =
    Extra.randomIdx r (Array.length keywords)
        |> (\i -> Array.get i keywords)
        |> Maybe.withDefault "key"

randomQuote : Float -> String
randomQuote r =
    Extra.randomIdx r (Array.length quotes)
        |> (\i -> Array.get i quotes)
        |> Maybe.withDefault "a perfect quote"

keywords : Array String
keywords =
    Array.fromList
        [ "Add", "Auth", "Bits", "Byte", "Book", "Box", "Break", "Brute", "Bugs"
        , "Caesar", "Cast", "Chain", "Char", "Code", "Con", "Cover", "Crack", "Cross"
        , "Cube", "Cycle", "Data", "Deck", "Decode", "Deep", "DES", "Digit"
        , "Disk", "Div", "Door", "ECB", "Encode", "Enigma", "Entry", "Fax", "Field"
        , "Figure", "File", "Gate", "Hash", "Hide", "Hill", "Hop", "IV", "Jazz"
        , "Jitter", "Key", "Keys", "Layer", "Len", "Line", "Link", "Log", "Logic"
        , "Loop", "MAC", "Map", "Mark", "Math", "Meet", "Melon", "Mode", "Mod", "Mono"
        , "Msg", "Nil", "Nix", "Noise", "Nonce", "Null", "Pad", "Pass", "Pipe", "Plan"
        , "Poly", "Porta", "Prep", "Pub", "RSA", "Run", "Rune", "Salt", "Scram", "Seal"
        , "Sec", "Secret", "Send", "Shift", "Sign", "Spy", "Sub", "Suite", "Sync", "Sym"
        , "Text", "Trap", "Vail", "XOR", "Zero", "AES", "Arc", "Args", "Atom", "Band"
        , "Base", "Batch", "Bind", "Blob", "Block", "Cipher", "Close", "Cloud", "Combo"
        , "Comp", "Core", "Crc", "Curve", "Diffie", "Digest", "Diff", "ECC", "End", "Engage"
        , "Equal", "Evt", "Flow", "Func", "Gamma", "Gen", "Hand", "Head", "Hex"
        , "Info", "Input", "Inte", "Ip", "Item", "Join", "Jump", "Kb", "Lck", "Lead", "Left"
        , "List", "Lock", "Mask", "Max", "Min", "Mix", "Msgid", "Net", "New", "Next", "Node"
        , "Open", "Output", "Pair", "Param", "Part", "Path", "Perm", "Pin", "Post", "Priv"
        , "Proc", "Prot", "Prng", "Psk", "Pto", "Rand", "Recv", "Reg", "Rem", "Rnd", "Root"
        , "Seed", "Select", "Semi", "Sha", "Skip", "Slice", "Slot", "Src", "Start", "Step"
        , "Stop", "Tag", "Tls", "Token", "Topo", "Tup", "Type", "Udp", "Unic", "Url", "Val"
        , "Var", "Vector", "Verify", "View", "Void", "Wan", "Word"
        ]

quotes : Array String
quotes =
    Array.fromList
        [ "pencils and quadrille pads"
        , "all flourishing is mutual"
        , "a goal without a plan is just a wish"
        , "a library is more precious than a bank"
        , "a library is thought in cold storage"
        , "a man is known by the books he reads"
        , "a penny saved is a penny earned"
        , "a stumble may prevent a fall"
        , "a true friend is the best possession"
        , "a witty saying proves nothing"
        , "achievement has no color"
        , "action expresses priorities"
        , "affection is catching"
        , "aim higher in case you fall short"
        , "all knowledge is worth having"
        , "all the funs in how you say a thing"
        , "always do what you are afraid to do"
        , "an artist is his own fault"
        , "anything worthy is worth the fight"
        , "art is science made clear"
        , "assertion is not proof"
        , "awake arise or be for ever falln"
        , "baking is both an art and a science"
        , "be so good they cant ignore you"
        , "birds dont eat canned worms"
        , "books are a uniquely portable magic"
        , "books do furnish a room"
        , "but what is life if you dont live it"
        , "can we survive technology"
        , "cleverness is not wisdom"
        , "conflicts are expensive"
        , "conflicts have small beginnings"
        , "darkness feeds on apathy"
        , "do you need space join nasa"
        , "dont act your role be yourself"
        , "dont just listen understand it"
        , "dont just wish for success earn it"
        , "dont spell part backwards its a trap"
        , "dont try to fix me im not broken"
        , "encourage your own greatness"
        , "enough talk now read"
        , "even a child is known by his doings"
        , "excuse me while i succeed"
        , "failure has its successes"
        , "fake life is expensive"
        , "find a voice in a whisper"
        , "fortune assists the bold"
        , "give me a museum and ill fill it"
        , "gravity always wins"
        , "habit is ten times nature"
        , "happiness is answering your calling"
        , "happiness lies in hope"
        , "happy is as happy does"
        , "hardships make or break people"
        , "he who is good is happy"
        , "helpfulness is the enemy of greed"
        , "history is a great dust heap"
        , "i am not omniscient but i know a lot"
        , "i am the captain of my soul"
        , "i dont like lollipops"
        , "i dwell in possibility"
        , "i know certain truths about life"
        , "i only know that i know nothing"
        , "i think that success is having fun"
        , "i worship the quicksand he walks in"
        , "ideas shape the course of history"
        , "if obstacles are large jump higher"
        , "if we listen we shall learn"
        , "if you cant win by reason go for volume"
        , "if you dont laugh youll cry"
        , "if you want to be happy be"
        , "im in the mood to multiply"
        , "im not stubborn my way is just better"
        , "imagine others complexly"
        , "in all things give thanks"
        , "in order to fail you must try first"
        , "its always too soon to quit"
        , "its not over until you win"
        , "its pretty confusing"
        , "ive got nothing to do today but smile"
        , "just be yourself there is no one better"
        , "keep calm and eat cookies"
        , "know what youre talking about"
        , "knowledge is power as well as fame"
        , "knowledge is strength"
        , "knowledge not shared remains unknown"
        , "leaders prioritize what they want"
        , "lets get things straight"
        , "life is a journey worth making"
        , "life is like a box of chocolates"
        , "life is more fun if you play games"
        , "living is more than just a pulse"
        , "living is my job and my art"
        , "love is the absence of judgment"
        , "luck is believing youre lucky"
        , "make today worth remembering"
        , "man is a toolmaking animal"
        , "math puns are the first sine of madness"
        , "may success knock your door always"
        , "meow means woof in cat"
        , "momentum builds success"
        , "more matter with less art"
        , "morning will come it has no choice"
        , "my geekness is aquivering"
        , "my main focus is on my game"
        , "mystery is never disproof"
        , "never confuse belief with knowledge"
        , "never fire a laser at a mirror"
        , "never follow the crowd"
        , "never forget your past"
        , "never ruin an apology with an excuse"
        , "nothing is fun until youre good at it"
        , "of all things i liked books best"
        , "ok so whats the speed of dark"
        , "once i get on a puzzle i cant get off"
        , "one can never have enough socks"
        , "one planet one experiment"
        , "order is heavens first law"
        , "our future is up to us"
        , "our true mentor in life is science"
        , "peace begins when expectations end"
        , "people are sheep tv is the shepherd"
        , "perfect is the enemy of good"
        , "perfection is an undiscovered jewel"
        , "quiet people have the loudest minds"
        , "reach for the stars"
        , "said sirius seriously"
        , "science doesnt take sides does it"
        , "science is magic that works"
        , "science is organized knowledge"
        , "science is the poetry of reality"
        , "shut your eyes and see"
        , "snoring keeps the monsters away"
        , "somewhere the zebra is dancing"
        , "start small and keep going"
        , "storms make trees take deeper roots"
        , "success is a decision not a gift"
        , "that was the week that was"
        , "the beautiful is always bizarre"
        , "the book you dont read wont help"
        , "the gods too are fond of a joke"
        , "the greatest ideas are the simplest"
        , "the medium is the message"
        , "the only joy in the world is to begin"
        , "the past can not be cured"
        , "the perfect is the enemy of the good"
        , "the present is a point just passed"
        , "the purpose of fun is to live it"
        , "the river is everywhere"
        , "the universe in a nutshell"
        , "there was i found always more to learn"
        , "think with your whole body"
        , "this book fills a muchneeded gap"
        , "those who dont jump will never fly"
        , "to be a success think of happiness"
        , "to be noble help others to succeed"
        , "to be too knowing is a downfall"
        , "to have hope is to be happy"
        , "to live is to be haunted"
        , "to those who will see the world waits"
        , "too many locks not enough keys"
        , "travel far enough you meet yourself"
        , "unbeing dead isnt being alive"
        , "universe consists of frozen light"
        , "we cannot just live any how"
        , "we convince by our presence"
        , "we made too many wrong mistakes"
        , "we must work while we have strength"
        , "we need no language to laugh"
        , "well done is better than well said"
        , "what dog cant bark a hot dog"
        , "what is a rebel a man who says no"
        , "what we think we become"
        , "which was to be proved"
        , "who can count the sand by the sea"
        , "whose life is it anyway"
        , "why dont you light that candle"
        , "why learn and innovate"
        , "wisdom is the daughter of experience"
        , "without knowledge we are weak"
        , "wonder is the seed of knowledge"
        , "written words can also sing"
        , "you can know a lot and still be stupid"
        , "you cannot predict the future"
        , "you may delay but time will not"
        , "your story is important"
        , "fortune does not change nature"
        , "the only journey is the one within"
        , "without hope there we fail to be happy"
        , "a good king is a public servant"
        , "good manners are part of good morals"
        , "patience is the key of content"
        , "some things better left unspoken"
        , "better ask twice than go wrong once"
        , "out of clutter find simplicity"
        , "glory is the reward of victory"
        , "peace is liberty in tranquility"
        , "age is a matter of feeling not of years"
        , "light not your candle at both ends"
        , "you cannot see beauty you feel it"
        , "let my honour be without stain"
        , "understanding develops slowly"
        , "necessity unites hearts"
        , "better leave than lack"
        , "boldness is an ill keeper of promise"
        , "boredom is the fear of self"
        , "a friend is a second self"
        , "nothing in this world happens by chance"
        , "distance lends enchantment to the view"
        , "how my achievements mock me"
        , "books are a life to ones soul"
        , "a mans fate is his own temper"
    ]